//go:build !ignore_autogenerated

/*
Copyright The ILM Authors.

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CzertainlyClusterIssuer) DeepCopyInto(out *CzertainlyClusterIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CzertainlyClusterIssuer.
func (in *CzertainlyClusterIssuer) DeepCopy() *CzertainlyClusterIssuer {
	if in == nil {
		return nil
	}
	out := new(CzertainlyClusterIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CzertainlyClusterIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CzertainlyClusterIssuerList) DeepCopyInto(out *CzertainlyClusterIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CzertainlyClusterIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CzertainlyClusterIssuerList.
func (in *CzertainlyClusterIssuerList) DeepCopy() *CzertainlyClusterIssuerList {
	if in == nil {
		return nil
	}
	out := new(CzertainlyClusterIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CzertainlyClusterIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CzertainlyIssuer) DeepCopyInto(out *CzertainlyIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CzertainlyIssuer.
func (in *CzertainlyIssuer) DeepCopy() *CzertainlyIssuer {
	if in == nil {
		return nil
	}
	out := new(CzertainlyIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CzertainlyIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CzertainlyIssuerList) DeepCopyInto(out *CzertainlyIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CzertainlyIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CzertainlyIssuerList.
func (in *CzertainlyIssuerList) DeepCopy() *CzertainlyIssuerList {
	if in == nil {
		return nil
	}
	out := new(CzertainlyIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CzertainlyIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpTransport) DeepCopyInto(out *HttpTransport) {
	*out = *in
	if in.DialTimeout != nil {
		in, out := &in.DialTimeout, &out.DialTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DialKeepAlive != nil {
		in, out := &in.DialKeepAlive, &out.DialKeepAlive
		*out = new(v1.Duration)
		**out = **in
	}
	if in.TLSHandshakeTimeout != nil {
		in, out := &in.TLSHandshakeTimeout, &out.TLSHandshakeTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ResponseHeaderTimeout != nil {
		in, out := &in.ResponseHeaderTimeout, &out.ResponseHeaderTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ExpectContinueTimeout != nil {
		in, out := &in.ExpectContinueTimeout, &out.ExpectContinueTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.IdleConnTimeout != nil {
		in, out := &in.IdleConnTimeout, &out.IdleConnTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxIdleConns != nil {
		in, out := &in.MaxIdleConns, &out.MaxIdleConns
		*out = new(int)
		**out = **in
	}
	if in.MaxIdleConnsPerHost != nil {
		in, out := &in.MaxIdleConnsPerHost, &out.MaxIdleConnsPerHost
		*out = new(int)
		**out = **in
	}
	if in.ClientTimeout != nil {
		in, out := &in.ClientTimeout, &out.ClientTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpTransport.
func (in *HttpTransport) DeepCopy() *HttpTransport {
	if in == nil {
		return nil
	}
	out := new(HttpTransport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuerSpec) DeepCopyInto(out *IssuerSpec) {
	*out = *in
	if in.HttpTransport != nil {
		in, out := &in.HttpTransport, &out.HttpTransport
		*out = new(HttpTransport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuerSpec.
func (in *IssuerSpec) DeepCopy() *IssuerSpec {
	if in == nil {
		return nil
	}
	out := new(IssuerSpec)
	in.DeepCopyInto(out)
	return out
}
