name: Test
on:
  pull_request:
    paths-ignore:
      - 'deploy/charts/**'
    branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - run: make test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - run: make -j1 kind-cluster deploy-cert-manager docker-build kind-load deploy e2e
      - run: make kind-export-logs E2E_ARTIFACTS_DIRECTORY=build/artifacts/e2e-logs
        if: failure()
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: e2e-logs
          path: build/artifacts/e2e-logs
